// 构建前自动同步 GitHub 公开仓库的 star 数。
//
// 设计要点：
// 1. 只读公开数据（stars / 仓库名），匿名调用 GitHub REST API，不需要任何 token。
// 2. 仓库列表从源码里的 github.com/Zaosusu/<repo> 链接自动提取，新增 skill 无需改这里。
// 3. 请求失败 / 超时 / 限流时**保留已有文件并正常退出**，绝不让构建挂掉。
// 4. 输出 src/data/skillStars.ts（带类型，避免依赖 resolveJsonModule）。

import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const OUT_FILE = join(ROOT, 'src', 'data', 'skillStars.ts');

const OWNER = 'Zaosusu';
const TIMEOUT_MS = 10000;

// 可选令牌：优先读环境变量 GITHUB_TOKEN。
// 在 GitHub Actions 里这个值是平台自动注入的临时凭证（仓库 settings 里无需配置任何 secret），
// 用它的唯一好处是把匿名限流 60 次/小时 提到 5000 次/小时，避免 CI 共享 IP 撞限流。
// 本地不设这个变量也能正常工作（匿名读取公开数据）。
const TOKEN = process.env.GITHUB_TOKEN || process.env.GH_TOKEN || '';

// 只同步「官网巴别图书馆」里展示的 skill，不多抓别的仓库。
// 权威来源就是 LibraryOfBabel.tsx 的 skillsData 数组——那里列了几个就同步几个。
const SCAN_FILE = join(ROOT, 'src', 'pages', 'LibraryOfBabel.tsx');

async function readSkillSources() {
  return readFile(SCAN_FILE, 'utf8');
}

// 从 skillsData 里抓 github.com/<owner>/<repo>，只认官网展示的 skill 条目
function extractRepos(source) {
  const re = new RegExp(`github\\.com/${OWNER}/([A-Za-z0-9._-]+)`, 'g');
  const found = new Set();
  for (const m of source.matchAll(re)) {
    const repo = m[1].replace(/\.git$/, '').replace(/['"`].*$/, '');
    if (repo) found.add(repo);
  }
  return [...found].sort();
}

async function fetchStars(repo) {
  const ctrl = new AbortController();
  const timer = setTimeout(() => ctrl.abort(), TIMEOUT_MS);
  try {
    const headers = {
      Accept: 'application/vnd.github+json',
      'User-Agent': 'zaosusu-site-build',
      'X-GitHub-Api-Version': '2022-11-28',
    };
    if (TOKEN) headers.Authorization = `Bearer ${TOKEN}`;
    const res = await fetch(`https://api.github.com/repos/${OWNER}/${repo}`, {
      headers,
      signal: ctrl.signal,
    });
    if (res.status === 404) return { ok: false, reason: 'repo not found' };
    if (res.status === 403 || res.status === 429) return { ok: false, reason: 'rate limited' };
    if (!res.ok) return { ok: false, reason: `HTTP ${res.status}` };
    const data = await res.json();
    if (typeof data.stargazers_count !== 'number') {
      return { ok: false, reason: 'no stargazers_count' };
    }
    return { ok: true, stars: data.stargazers_count };
  } catch (err) {
    return { ok: false, reason: err?.name === 'AbortError' ? 'timeout' : String(err?.message ?? err) };
  } finally {
    clearTimeout(timer);
  }
}

function render(stars, previous, syncedAt) {
  const keys = Object.keys(stars).sort();
  const lines = keys.map((k) => `  ${JSON.stringify(k)}: ${stars[k]},`);
  const changed = keys.filter((k) => previous[k] !== stars[k]);
  const sameSet =
    Object.keys(previous).length === keys.length && keys.every((k) => previous[k] === stars[k]);

  // 数据没变就复用上次的时间戳，避免每次构建都产生一次无意义改动
  const stamp = sameSet && previous.__syncedAt ? previous.__syncedAt : syncedAt;

  return `// AUTO-GENERATED by scripts/fetch-stars.mjs — 请勿手工编辑。
// 数据来源：GitHub 公开 REST API（匿名读取，无需 token）。
// 最后同步：${stamp}
${changed.length ? `// 本次更新：${changed.map((k) => `${k} ${previous[k] ?? '?'}→${stars[k]}`).join(', ')}\n` : '// 本次无变化。\n'}
export const SKILL_STARS: Record<string, number> = {
${lines.join('\n')}
};

export const SKILL_STARS_SYNCED_AT = ${JSON.stringify(stamp)};
`;
}

// 读取已有文件里的 star 数（失败回退用）
async function readPrevious() {
  if (!existsSync(OUT_FILE)) return {};
  try {
    const mod = await import(`file://${OUT_FILE.replace(/\\/g, '/')}?t=${Date.now()}`);
    const prev = { ...(mod.SKILL_STARS ?? {}) };
    if (typeof mod.SKILL_STARS_SYNCED_AT === 'string') {
      Object.defineProperty(prev, '__syncedAt', {
        value: mod.SKILL_STARS_SYNCED_AT,
        enumerable: false,
      });
    }
    return prev;
  } catch {
    return {};
  }
}

async function main() {
  const previous = await readPrevious();

  const source = await readSkillSources();
  const repos = extractRepos(source);

  if (repos.length === 0) {
    console.warn('[stars] 未从 skillsData 提取到任何仓库，跳过同步。');
    return;
  }

  console.log(`[stars] 待同步 ${repos.length} 个仓库：${repos.join(', ')}`);

  const results = await Promise.all(repos.map(async (r) => [r, await fetchStars(r)]));

  const stars = {};
  const failed = [];
  for (const [repo, res] of results) {
    if (res.ok) {
      stars[repo] = res.stars;
    } else if (previous[repo] !== undefined) {
      // 回退到上一次的值
      stars[repo] = previous[repo];
      failed.push(`${repo}(${res.reason}→沿用旧值)`);
    } else {
      failed.push(`${repo}(${res.reason}→无旧值,跳过)`);
    }
  }

  if (Object.keys(stars).length === 0) {
    console.warn(`[stars] 全部请求失败，保留原文件。详情：${failed.join('; ')}`);
    return;
  }

  if (failed.length) {
    console.warn(`[stars] 部分失败（已回退）：${failed.join('; ')}`);
  }

  const syncedAt = new Date().toISOString();
  const next = render(stars, previous, syncedAt);

  if (existsSync(OUT_FILE) && (await readFile(OUT_FILE, 'utf8')) === next) {
    console.log('[stars] 无变化，未写文件。');
    return;
  }

  await mkdir(dirname(OUT_FILE), { recursive: true });
  await writeFile(OUT_FILE, next, 'utf8');
  console.log(`[stars] 已写入 ${OUT_FILE}`);
}

// 任何意外都不阻断构建
main().catch((err) => {
  console.warn(`[stars] 同步失败（不影响构建）：${err?.message ?? err}`);
});
