// AUTO-GENERATED by scripts/fetch-stars.mjs — 请勿手工编辑。
// 数据来源：GitHub 公开 REST API（匿名读取，无需 token）。
// 最后同步：2026-09-21T14:10:33.453Z
// 本次无变化。

export const SKILL_STARS: Record<string, number> = {
  "agent-usage-skill": 0,
  "form-autofill-skill": 0,
  "imgbox-skill": 0,
  "live-class-skill": 1,
  "multi-agent-async-workflow": 7,
  "resume-onepager-skill": 0,
  "schedule-onepager-skill": 0,
  "zhicheng-shenbao-skill": 1,
};

export const SKILL_STARS_SYNCED_AT = "2026-09-21T14:10:33.453Z";
